#!/usr/bin/env bash
if [[ $# -lt 1 ]]; then
    printf "Usage:\t%s <file_name>\n" $(basename $0)
    exit 1
fi

#FILE="$1"

for FILE in "$@"; do
    if [[ ! -f $FILE ]]; then
	printf "File \'%s\' dose not exist.\n" "$FILE"
	continue
    fi

    TOTAL=$(wc -l "$FILE" |awk '{print $1}')
    COUNT=0
    MAX=0
    PROGRESS=0
    printf "%7s%%\t%s\r" " " "$FILE" >&2
    while read LINE; do
	LEN=${#LINE};
	if [[ $MAX -lt $LEN ]]; then
	    MAX=$LEN
	fi
	((COUNT++))
	PROGRESS=$(echo "scale=2;100*$COUNT/$TOTAL" |bc)
	printf "%7s\r" $PROGRESS >&2
	#printf "\033[A" >&2
	#tput el1 >&2
    done <"$FILE"
    printf "\r"
    tput el >&2
    printf "%8s\t%s\n" "$MAX" "$FILE"
done
